on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
permissions:
  contents: write
jobs:
  fetch-upstream:
    runs-on: ubuntu-latest
    name: Fetch Upstream
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure git
        run: |
          git config --global user.name "CI Bot"
          git config --global user.email "hlouzada@users.noreply.github.com"
          git remote add upstream https://github.com/ppfeufer/adguard-filter-list.git
          default_branch=${{ github.event.repository.default_branch }}
        shell: bash
      - name: Fetch and merge
        id: fetch-merge
        run: |
          git fetch upstream
          git checkout $default_branch
          lines=$( git diff $default_branch..upstream/$default_branch -- . ':(exclude).github/**' | wc -l )
          echo "Number of detected line changes: $lines"
          if [ $lines -gt 0 ]; then
            git merge upstream/main
            git push
          fi
        shell: bash
